# Generated by Django 3.2.23 on 2024-01-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminkomo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excel',
            new_name='ExcelFile',
        ),
    ]
