# Generated by Django 3.2.23 on 2024-01-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkomo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(unique=True, upload_to='data_excel/'),
        ),
    ]
