# Generated by Django 3.2.13 on 2023-12-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forfait',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
