# Generated by Django 3.2.13 on 2023-12-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_forfait_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
    ]
