# Generated by Django 3.2.13 on 2023-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_general', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='totalcredit',
            options={'ordering': ['client']},
        ),
    ]
