# Generated by Django 3.2.13 on 2023-12-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20231223_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_total_credit', to='client.totalcredit'),
        ),
    ]
