# Generated by Django 3.2.13 on 2023-12-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_total_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='total_credit',
        ),
    ]
