# Generated by Django 3.2.13 on 2023-12-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_client_total_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('data_forfait', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.totalcredit')),
            ],
        ),
    ]
