# Generated by Django 3.2.13 on 2023-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_retraitcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitcredit',
            name='data_mo',
            field=models.CharField(blank=True, default='0 Mo', max_length=1000, null=True),
        ),
    ]
