# Generated by Django 3.2.13 on 2023-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_retraitcredit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitcredit',
            name='quantite',
            field=models.IntegerField(choices=[(50, '50'), (100, '100'), (150, '150'), (200, '200'), (250, '250'), (300, '300'), (350, '350'), (400, '400')], default=50),
        ),
    ]
