# Generated by Django 3.2.13 on 2023-12-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_retraitcredit_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retraitcredit',
            name='data_mo',
        ),
        migrations.AlterField(
            model_name='retraitcredit',
            name='data_forfait',
            field=models.IntegerField(choices=[(50, '50 Mo'), (100, '100 Mo'), (150, '150 Mo'), (200, '200 Mo'), (250, '250 Mo'), (300, '300 Mo'), (350, '350 Mo'), (400, '400 Mo')], default=50),
        ),
        migrations.AlterField(
            model_name='retraitcredit',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
