# Generated by Django 3.2.13 on 2023-12-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20231230_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitcredit',
            name='data_forfait',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retraitcredit',
            name='quantite',
            field=models.IntegerField(choices=[(100, '100 crédits'), (200, '200 crédits'), (300, '300 crédits'), (400, '400 crédits')], default=50),
        ),
    ]
