# Generated by Django 4.2.8 on 2023-12-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20231231_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitcredit',
            name='quantite',
            field=models.IntegerField(choices=[(50, '50 crédits'), (75, '75 crédits'), (100, '100 crédits'), (125, '125 crédits'), (150, '150 crédits'), (175, '175 crédits'), (200, '200 crédits')], default=50),
        ),
    ]
